chain:
  bech32_prefix: {{ .Cored.AddressPrefix }}
  modules:
    - modules
    - messages
    - auth
    - bank
    - consensus
    - gov
    - mint
    - slashing
    - staking
    - distribution
    - actions
node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://{{ .Cored.Host }}:{{ .Cored.PortRPC }}
      max_connections: 20
    grpc:
      address: {{ .Cored.Host }}:{{ .Cored.PortGRPC }}
      insecure: true

parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  start_height: 1
  fast_sync: false
  genesis_file_path: {{ .Cored.GenesisFilePath }}
  average_block_time: 1.5s

database:
  name: {{ .Postgres.DB }}
  host: {{ .Postgres.Host }}
  port: {{ .Postgres.Port }}
  user: {{ .Postgres.User }}
  schema: public
  max_open_connections: 1
  max_idle_connections: 1
  partition_size: 100000
  partition_batch: 1000

logging:
  level: debug
  format: text

actions:
  port: {{ .Port }}
