{
 "title": "Callisto",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "callisto_block_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful proposals",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(cometbft_consensus_expected_proposers_sum{}[$__range])) by (validator_address)) / (sum(increase(cometbft_consensus_expected_proposers_count{}[$__range])) by (validator_address))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Vote time deviation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(increase(cometbft_consensus_vote_deviation_sum{}[$__range])) by (validator_address)) / (sum(increase(cometbft_consensus_vote_deviation_count{}[$__range])) by (validator_address))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful votes",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(cometbft_consensus_expected_voters_sum{}[$__range])) by (validator_address)) / (sum(increase(cometbft_consensus_expected_voters_count{}[$__range])) by (validator_address))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}