chain:
  bech32_prefix: {{ .Cored.AddressPrefix }}
  modules:
    - telemetry
    - addresses
    - assetft
    - assetnft
    - auth
    - bank
    - consensus
    - customparams
    - daily refetch
    - dex
    - distribution
    - feegrant
    - feemodel
    - gov
    - message_type
    - mint
    - pricefeed
    - slashing
    - staking
    - upgrade
    - bridge 
node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://{{ .Cored.Host }}:{{ .Cored.PortRPC }}
      max_connections: 20
    grpc:
      address: {{ .Cored.Host }}:{{ .Cored.PortGRPC }}
      insecure: true
    api:
      address: http://{{ .Cored.Host }}:{{ .Cored.PortAPI }}
parsing:
  workers: 1
  start_height: 1
  average_block_time: 1.5s
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  genesis_file_path: {{ .Cored.GenesisFilePath }}
database:
  url: postgresql://{{ .Postgres.User }}@{{ .Postgres.Host }}:{{ .Postgres.Port }}/{{ .Postgres.DB }}?sslmode=disable&search_path=public
  name: {{ .Postgres.DB }}
  host: {{ .Postgres.Host }}
  port: {{ .Postgres.Port }}
  user: {{ .Postgres.User }}
  schema: public
  max_open_connections: 1
  max_idle_connections: 1
  partition_size: 100000
  partition_batch: 1000
  ssl_mode_enable: "false"
  ssl_root_cert: ""
  ssl_cert: ""
  ssl_key: ""

telemetry:
  port: 5001

logging:
  level: info
  format: text

actions:
  host: 0.0.0.0
  port: {{ .Port }}

pricefeed:
  tokens:
    - name: coreum
      units:
        - denom: coreum
          exponent: 6
          price_id: coreum
bridge:
  contract_address: {{ .ContractAddress }}
