name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
              echo ::set-output name=release-candidate::true
          fi
      - name: Release
        if: steps.check-tag.outputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
      - name: Release-candidate
        if: steps.check-tag.outputs.release-candidate == 'true'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
